- lib/active_record/connection_adapters/clickhouse/oid/date_time.rb
The DateTime OID calls `strftime` method on DateTime value in case if the value does not act like time. The problem is that `nil` does not act like time and doesn't have `strftime` method so that creating an object with `{ ... datetime_field: nil, ... }` leads to exception.
> Allow to pass nil value to DateTime field

- README.md
- lib/active_record/connection_adapters/clickhouse/schema_definitions.rb
- lib/active_record/connection_adapters/clickhouse_adapter.rb
I was using `ENGINE = VersionedCollapsingMergeTree(sign, version)` but when trying to load the schema file, it would raise an exception because `sign` must be an an `Int8`. This adds support for specifying the integer size with `:limit` and signed/unsigned with `:unsigned => false`. These details are explained in the README patch.
This does not fix the fact that the schema file was probably dumped wrong. I'm not sure where to look to fix that issue. I had originally created the tables with an `execute("CREATE TABLE ...")` migration - maybe part of the problem.
> Adding support for all integer types through :limit and :unsigned

- lib/clickhouse-activerecord/tasks.rb
Schema / structure loads includes `INSERT` statements, which would previously fail as it would put `FORMAT JSONCompact` on the end.
This PR special cases `INSERT` statements, and ignores the empty queries.
> Fix schema load failure due to INSERT statements

- clickhouse-activerecord.gemspec
- lib/active_record/connection_adapters/clickhouse/schema_statements.rb
- lib/active_record/connection_adapters/clickhouse_adapter.rb
Hi!  My team and I use this gem quite a bit and would love to share some contributions we've made.  This PR contains a handful of small changes that we've made to integrate it with our existing codebases.  I'm happy to split this up into multiple PRs if you feel the changes are too disparate, but we thought they were small enough that they could go together.
- Filters out Clickhouse-internal matviews that are normally exported, which start with `.inner_id.`
- `reverse_order!` has been rewritten with a `prepend` to leverage `super`, instead of copying and pasting any changes to the method in future AR versions.
- `arel_table` only returns a `ClickhouseActiverecord::Arel::Table` if the model uses Clickhouse, which is necessary if Clickhouse is only one of multiple databases in use.
- …
> Various compatibility fixes

- lib/active_record/connection_adapters/clickhouse_adapter.rb
`rake db:schema:dump:clickhouse` doesn't record the precision and scale of `Decimal` columns. For example, instead of the expected:
``` rb
t.decimal "my_decimal_column", precision: 14, scale: 2
```
it just stores:
``` rb
t.decimal "my_decimal_column"
```
I did quite a bit of digging and figured out that this is because the Rails schema dumper—the default one—doesn't permit spaces after commas in _e.g._ `Decimal(14, 2)`, and ClickHouse dumps the schema with this space. So this PR overrides the relevant methods to permit this space.
The methods that this overrides are in:
https://github.com/rails/rails/blob/4d5a570cfe1890f71a1d198a5fe40d528f2b60d4/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L770-L779
``` rb
def extract_scale(sql_type)
case sql_type
when …
```
> Fix precision and scale extraction of decimal fields

- lib/active_record/connection_adapters/clickhouse_adapter.rb
Net::HTTP defaults to 2 seconds, which is much shorter than ClickHouse's
10 seconds.
Ideally we should respect the Keep-Alive response header, but that
responsibility should be handled by the HTTP transport, and it's a
limitation of Net::HTTP's implementation - net-http-persistent has code
to handle this as an example.
> Use ClickHouse default KeepAlive timeout of 10 seconds

- lib/active_record/connection_adapters/clickhouse_adapter.rb
These are a couple of changes I needed to make in order to get the `connection.create_table` method to work.
The symptoms are:
- For 481598a, it was trying to send the `select engine from system.databases` query to Postgres, presumably because it's our primary database. My guess is this line accidentally assumed that ClickHouse is the primary database, which for us isn't the case. This just drops the `ActiveRecord::Base.connection` so that it will use the `select_one` from the same `ClickhouseAdapter`.
- For 67390f9, it was trying to add `FORMAT JSONCompact` to the `CREATE TABLE` query, which is a syntax error.
We're on Ruby 3.0.4, Rails 6.1.4.4, ClickHouse 21.8.14.5. Open to feedback on making this more robust.
> Fixes to create_table method

- lib/active_record/connection_adapters/clickhouse_adapter.rb
- spec/cases/migration_spec.rb
- spec/fixtures/migrations/dsl_create_table_with_cluster_name_alias/1_create_some_table.rb
- spec/spec_helper.rb
Hello!
I tried to use an alias in `cluster_name` with config:
```yaml
...
cluster_name: '{cluster}'
replica_name: '{replica}'
...
```
But I got an error on database creation:
```
Code: 62. DB::Exception: Syntax error: failed at position 47 ('{'): {cluster}. Expected one of identifier, string literal. (SYNTAX_ERROR) (version 22.5.2.53 (official build))
```
I found a workaround:
```yaml
...
cluster_name: "'{cluster}'"
replica_name: '{replica}'
...
```
It works for database creation, but it doesn't for replicated tables because of interpolation: https://github.com/PNixx/clickhouse-activerecord/blob/c2a4f86f35974f5993be1711d930379442b9ad23/lib/active_record/connection_adapters/clickhouse_adapter.rb#L376
Here's a small pull request. It allows to do:
```yaml
...
cluster_name: '{cluster}' …
```
> Possibility to use an alias in cluster name

- lib/clickhouse-activerecord/migration.rb
This PR fixing issue #75 :
Current schema_migrations table structure is:
```
CREATE TABLE schema_migrations
(
`version` String,
`active` Int8 DEFAULT 1,
`ver` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(ver)
PARTITION BY version
ORDER BY version
SETTINGS index_granularity = 8192;
```
So it will create 1 partition for each version. Default value for max_partitions_per_insert_block is 100, and actually it's bad to have too many partitions, so it's better to remove PARTITION BY from schema_migrations table definition.
Other wise if you have more then 100 migrations and try to do db:structure:load
You will got:
```
ActiveRecord::ActiveRecordError: Response code: 500:
Code: 252. DB::Exception: Too many partitions for single INSERT block (more than 100). The limit is controlled by …
```
> Fix error on schema_migrations table when more then 100 migrations

- lib/active_record/connection_adapters/clickhouse_adapter.rb
- spec/cases/migration_spec.rb
- spec/fixtures/migrations/dsl_drop_table_sync/1_create_some_table.rb
- spec/fixtures/migrations/dsl_drop_table_sync/2_drop_some_table.rb
Hello!
Right now, it's impossible to use the "SYNC" keyword for "DROP TABLE". This PR adds this possibility.
Documentation: https://clickhouse.com/docs/en/sql-reference/statements/drop
```
If the SYNC modifier is specified, the entity is dropped without delay.
```
> add "SYNC" keyword support for "DROP TABLE"

- lib/active_record/connection_adapters/clickhouse/oid/uuid.rb
- lib/active_record/connection_adapters/clickhouse_adapter.rb
- spec/cases/model_spec.rb
- spec/fixtures/migrations/add_sample_data/1_create_sample_table.rb
Without that change dump of every table containing Bool type column puts the following message instead of proper table structure in `db/schema.rb`:
```
```
> register Bool and UUID in type map

- lib/arel/visitors/clickhouse.rb
- spec/cases/model_spec.rb
I needed to dive into Arel for some queries, and I found that #matches was using LIKE instead of ILIKE. This PR is basically a copy/paste from Arel::Visitors::PostgreSQL:
https://github.com/rails/rails/blob/316338acf76c34b529e7d883a916ace798ad8efa/activerecord/lib/arel/visitors/postgresql.rb#L7-L27
> Use ILIKE for model.arel_table[:column]#matches

- lib/active_record/connection_adapters/clickhouse/oid/uuid.rb
- lib/active_record/connection_adapters/clickhouse_adapter.rb
- spec/cases/model_spec.rb
This PR backports UUID column support to the Rails 7.0 branch.
> Backport UUID column support

- lib/active_record/connection_adapters/clickhouse/schema_statements.rb
- spec/cases/model_spec.rb
- spec/fixtures/migrations/add_sample_data/1_create_sample_table.rb
This PR aims to add support for binary string. The main problem is that the 'JSONCompact' format removes invalid UTF-8 bytes. To fix this I needed to change the format to some 'EachRow' version. I chose 'JSONCompactEachRowWithNamesAndTypes'.
Any suggestions are welcome.
Documentation Sugestion: "Use the `JSONEachRow` format if you are sure that the data in the table can be formatted as JSON without losing any information."
Reference: https://clickhouse.com/docs/en/interfaces/formats#json-selecting-data
Issues: https://github.com/PNixx/clickhouse-activerecord/issues/57
> Add support for binary string

- lib/active_record/connection_adapters/clickhouse_adapter.rb
Following up on @PauloMiranda98 's PR here: https://github.com/PNixx/clickhouse-activerecord/pull/116
I think he missed two places to update `process_response`. After the PR the arity of process_response is 2
```ruby
def process_response(res, format)
case res.code.to_i
when 200
...
end
```
The symptom is that I am getting the following error when trying to drop or create a clickhouse db
```
bin/rails aborted!
ArgumentError: wrong number of arguments (given 1, expected 2) (ArgumentError)
REDACTED/clickhouse-activerecord/lib/active_record/connection_adapters/clickhouse/schema_statements.rb:121:in `process_response'
REDACTED/clickhouse-activerecord/lib/active_record/connection_adapters/clickhouse_adapter.rb:316:in `block in drop_database' …
```
> Fix wrong method arguments

- lib/active_record/connection_adapters/clickhouse/oid/uuid.rb
- spec/single/model_spec.rb
This PR aims to fix non-canonical UUID. The Clickhouse accepts only [8-4-4-4-12 representation of uuid]( https://clickhouse.com/docs/en/sql-reference/data-types/uuid).
Before (`master` branch):
```ruby
irb(main):001:0> Model.where(id: 'invalid')
D, [2024-03-23T21:47:16.862694 #29099] DEBUG -- :   Clickhouse Model Load (2.6ms)  SELECT models.* FROM models WHERE models.id = NULL /* loading for pp */ LIMIT 11
=> []                                                                                          
irb(main):002:0> Model.where(id: 'abcd0123456789efdeadbeef01011010')
D, [2024-03-23T21:47:23.081674 #29099] DEBUG -- :   Clickhouse Model Load (3.4ms)  SELECT models.* FROM models WHERE models.id = 'abcd0123456789efdeadbeef01011010' /* loading for pp */ LIMIT 11
=> [#<Model:0x00007fab2ac94140 …
```
> Fix non-canonical UUID

- lib/active_record/connection_adapters/clickhouse/schema_statements.rb
- spec/fixtures/migrations/add_sample_data/1_create_sample_table.rb
- spec/single/model_spec.rb
I noticed a strange bug, where `95891.74` was converted to `9589174.000000001`. After investigation in turned out that the value was correctly stored in clickhouse, the data type was also correct. However it seemed that down the line it was converted to a float somewhere. It turned out it was the JSON parsing that converts numeric values to Floats. 
```ruby
decimal = ActiveModel::Type::Decimal.new(precision: 38, scale: 16, limit: nil)
decimal.cast(JSON.parse("95891.74"))
decimal.cast(JSON.parse("95891.74", decimal_class: BigDecimal))
```
So, telling JSON to convert all numerics to BigDecimal helps with further precision handling.
> Fix precision loss due to JSON float parsing

- lib/active_record/connection_adapters/clickhouse/schema_statements.rb
- lib/active_record/connection_adapters/clickhouse_adapter.rb
- lib/clickhouse-activerecord/schema_dumper.rb
- lib/clickhouse-activerecord/tasks.rb
- spec/cluster/migration_spec.rb
- spec/fixtures/migrations/dsl_create_function/1_create_some_function.rb
- spec/fixtures/migrations/plain_function_creation/1_create_some_function.rb
- spec/single/migration_spec.rb
- spec/spec_helper.rb
Adds support for User-Defined functions dump/load to structure.sql
https://clickhouse.com/docs/en/sql-reference/statements/create/function
I wasn't able to just run the specs in this repo from just cloning it, I had to first create database from the config I had in another repo, in order to then run the specs from this repo. It would be nice to either add some more documentation or make this repo self-contained for running specs.
> Support functions

- lib/clickhouse-activerecord/schema_dumper.rb
In Clickhouse, table names with periods are legal. The name must be quoted with backticks, however. This PR fixes the schema dumper to automatically quote column names with a period in them with backticks.
For column names with periods, this makes the schema restore for tests work correctly.  For columns without periods, the change will have no effect.
> Quote table names with periods when dumping schemas

- lib/active_record/connection_adapters/clickhouse_adapter.rb
When running separate databases for different environments (i.e. development, test) on the same machine, you will likely specify a different database name in `database.yml`. If you then run migrations in a different ENV, you will get schema changes as the database name will be dumped to the schema comments.
This change strips the database name from the schema, leaving only the table name.
Before:
```ruby
create_table "table_name" ...
```
Afteer:
```ruby
create_table "table_name" ...
```
> Normalize table name in schema dump

- lib/active_record/connection_adapters/clickhouse_adapter.rb
Fixes error described in #107; since clickhouse does not support transactions or savepoints, these methods should noop instead of raise a `NotImplementedError` which can originate from [this call site](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L418).
> Noop savepoint functionality

- lib/arel/visitors/clickhouse.rb
- spec/single/model_spec.rb
```ruby
1) Model sample #find_by finds the record
Failure/Error: collector << quote_table_name(o.relation.table_alias || o.relation.name) << '.' unless collector.value.start_with?('DELETE FROM ') || collector.value.include?(' UPDATE ')
NoMethodError:
undefined method `start_with?' for [["SELECT", " "], []]:Array
```
> Fix `#find_by`

- .gitignore
- README.md
- lib/active_record/connection_adapters/clickhouse/oid/map.rb
- lib/active_record/connection_adapters/clickhouse/schema_creation.rb
- lib/active_record/connection_adapters/clickhouse/schema_definitions.rb
- lib/active_record/connection_adapters/clickhouse/schema_statements.rb
- lib/active_record/connection_adapters/clickhouse_adapter.rb
- lib/clickhouse-activerecord/schema_dumper.rb
- spec/fixtures/migrations/add_map_datetime/1_create_verbs_table.rb
- spec/fixtures/migrations/dsl_table_with_fixed_string_creation/1_create_some_table.rb
- spec/fixtures/migrations/dsl_table_with_low_cardinality_creation/1_create_some_table.rb
- spec/single/migration_spec.rb
- spec/single/model_spec.rb
[Clickhouse Datatype Docs](https://clickhouse.com/docs/en/sql-reference/data-types/map)
Adapted from [this commit](https://github.com/huntresslabs/clickhouse-activerecord/commit/0d9db1d3ab4bac659be4e864e5041bd728807f62) but adapted to be similar to the existing `Array` datatype implementation.
> Add support for Map datatype

- lib/clickhouse-activerecord/tasks.rb
It currently automatically adds `FORMAT JSONCompact` at the end of the sql, and that fails when running `db:schema:load`:
```
ActiveRecord::StatementInvalid: ActiveRecord::ActiveRecordError: Response code: 400:
Code: 62. DB::Exception: Syntax error: failed at position 261 ('FORMAT') (line 7, col 2): FORMAT JSONCompact. Expected one of: token, Dot, OR, AND, IS NOT DISTINCT FROM, IS NULL, IS NOT NULL, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, REGEXP, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV, end of query. (SYNTAX_ERROR) (version 23.9.6.20 (official build))
```
Did not find any tests for these tasks, please point me in the right direction if they exist.
> Fix for function creation in structure.sql

- lib/active_record/connection_adapters/clickhouse_adapter.rb
- lib/arel/nodes/grouping_sets.rb
- lib/arel/visitors/clickhouse.rb
- lib/core_extensions/active_record/relation.rb
- spec/single/model_spec.rb
Implements [`GROUP BY GROUPING SETS`](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/grouping_function#grouping-sets). (Haven't done `CUBE` or `ROLLUP` yet.)
Example:
```ruby
users = User.group_by_grouping_sets([], [:name], [:name, :age]).select(:name, :age, 'count(*)')
```
generates:
```sql
SELECT name, age, count(*) FROM users GROUP BY GROUPING SETS ( (), (name), (name, age) )
```
Accepts arrays of strings, symbols, and Arel nodes, as well as any arbitrary mix of them.
> Add `group_by_grouping_sets` query method

- lib/active_record/connection_adapters/clickhouse_adapter.rb
- lib/clickhouse-activerecord/schema_dumper.rb
- spec/cluster/migration_spec.rb
- spec/fixtures/migrations/dsl_create_function/1_create_some_function.rb
- spec/single/migration_spec.rb
Fixes ##145
In a rails app, with existing Clickhouse schema w/a function defined, a `rails db:schema:load` will not always succeed; this is because the function may already exist.
```
Code: 609. DB::Exception: User-defined function 'uuid7ToDateTime' already exists. (FUNCTION_ALREADY_EXISTS) (version 23.9.6.20 (official build))
```
This can be addressed in at least two ways:
1. Guard the `CREATE FUNCTION` statement with `IF NOT EXISTS`; this would prevent trying to create the function, however, it also does not guarantee that the function is up-to-date with the schema
2. Use `CREATE OR REPLACE FUNCTION` instead. This has the benefit of ensuring the function is up-to-date with the schema
This commit pursues option #2. It adds a `force` option to the `create_function` method definition; …
> Add support for `CREATE FUNCTION` and `CREATE OR REPLACE FUNCTION`; the later in schema loading

- lib/active_record/connection_adapters/clickhouse_adapter.rb
- lib/arel/nodes/limit_by.rb
- lib/arel/visitors/clickhouse.rb
- lib/core_extensions/active_record/relation.rb
- lib/core_extensions/arel/nodes/select_statement.rb
- lib/core_extensions/arel/select_manager.rb
- spec/single/model_spec.rb
- spec/spec_helper.rb
- `LIMIT 1 BY field` clause is a very performant alternative for de-duplication. It's better than a `FINAL` or `GROUP BY`  on large sets.
- Add the support of this clause for the gem
Usage : 
```ruby
events = Event.limit_by(1, :event_key)
```
- NOTE: you can't use aggregate functions with a `LIMIT BY` without grouping, if you want to do so, you should use CTE, eg:
```ruby
events = Events.limit_by(1, :event_key)
sql = <<-SQL
with events as (#{events.to_sql})
SELECT count()
FROM events
SQL
Events.connection.select_value(sql)
```
- TODO: Add support for a list of fields `limit_by(<Integer>, <[Symbol]> or <[String]>`
> feat(limit_by): Add support for LIMIT BY clause

- lib/clickhouse-activerecord/schema_dumper.rb
Mitigates #171 by including primary key columns in the column definition if the primary key is not named `id`. This mirrors behavior prior to `ddfa259bbec88aefa3eaf2942392b8473a477601` while continuing to omit the primary key column if the name is `id`.
This is likely only a partial solution that seems like the best short-term path forward. A better long-term solution likely relies on #172 being solved such that passing `id: :TYPE_NOT_UInt32` is respected. This would also need to include non-integer data types such as `:datetime`.
> Include column definitions in schema dump if the column name is not `id`

- lib/clickhouse-activerecord/schema_dumper.rb
Before:
```sql
create_function "uuid7ToBeginningOfDay", "input -> toUUID(concat(hex(reinterpretAsUInt64(reverse(unhex(substring(hex(input), 1, 12)))) - (reinterpretAsUInt64(reverse(unhex(substring(hex(input), 1, 12)))) % 86400000)), \'00000000000000000000\'))", force: true
create_function "uuid7ToDateTime", "input -> fromUnixTimestamp64Milli(reinterpretAsUInt64(reverse(unhex(substring(hex(input), 1, 12)))))", force: true
create_function "uuidToBeginningOfDayDateTime", "input -> reinterpretAsUInt64(reverse(unhex(substring(hex(input), 1, 12))))", force: true
```
After:
```sql
create_function "uuid7ToBeginningOfDay", "input -> toUUID(concat(hex(reinterpretAsUInt64(reverse(unhex(substring(hex(input), 1, 12)))) - (reinterpretAsUInt64(reverse(unhex(substring(hex(input), 1, 12)))) % 86400000)), …
```
> Add blank line after create_function in schema

- lib/active_record/connection_adapters/clickhouse/oid/map.rb
- lib/active_record/connection_adapters/clickhouse/schema_creation.rb
- lib/clickhouse-activerecord/schema_dumper.rb
- spec/fixtures/migrations/add_array_datetime/1_create_actions_table.rb
- spec/fixtures/migrations/add_map_datetime/1_create_verbs_table.rb
- spec/fixtures/migrations/dsl_table_with_fixed_string_creation/1_create_some_table.rb
- spec/fixtures/migrations/dsl_table_with_low_cardinality_creation/1_create_some_table.rb
- spec/single/migration_spec.rb
- spec/single/model_spec.rb
The latest version [added support for `Map`](https://github.com/PNixx/clickhouse-activerecord/pull/144) (Thank you @danielwestendorf!)
At [Lago](https://github.com/getlago/lago), we forked this gem to add support for map but never took the time to open a PR with our change (sorry!). I'm updating our code to use the gem as much as possible. Our implementation was slightly different but very close.
The big missing feature is support for arrays inside maps like `{ key: [1, 2, 3] }`, which I'm adding in this PR.
We'll be running it in production this week and we'll let you know how it goes.
What do you think @danielwestendorf ? Did you get to work with maps of arrays.
> Add Array support to Map

- lib/clickhouse-activerecord/schema_dumper.rb
Partially fixes #172.
Previously schema would be dumped as such:
```ruby
create_table "my_table", id: :integer, limit: 2, unsigned: true do |t|
...
end
```
`limit` and `unsigned` would be ignored, resulting in an incorrect representation of the schema.
After it will specify the correct Clickhouse-native type:
```ruby
create_table "my_table", id: :uint8 do |t|
...
end
```
It does not address non-`id` named primary keys.
> Maintain primary key type specificity

- lib/active_record/connection_adapters/clickhouse/schema_statements.rb
- lib/clickhouse-activerecord/schema_dumper.rb
Dependent on #180
+ sorts functions when dumping schema for consistent schema changes
+ reliably sorts views and materialized views in schema
Previously, functions where dumped in an unsorted fashion, resulting in changes to the schema when no actual changes where made.
Previously, views and materialized views were reliably placed after tables, however, a sorted order of those views was not enforced so the order of the views would change when no actual changes where made.
> Reliably sort functions, views, and materialized views in schema

- lib/active_record/connection_adapters/clickhouse/schema_statements.rb
- lib/clickhouse-activerecord/tasks.rb
- spec/fixtures/migrations/plain_function_creation/1_create_some_function.rb
- spec/single/migration_spec.rb
This PR contains a couple small improvements to function dumps into structure.sql:
1. Preserve newlines, in case there are multi-line strings inside the function body
2. Sort functions by name so it's deterministic and behaves like tables
> Improve function dumps

- lib/active_record/connection_adapters/clickhouse/oid/map.rb
- lib/active_record/connection_adapters/clickhouse/table_definition.rb
- lib/active_record/connection_adapters/clickhouse_adapter.rb
Adds support for the `limit` option when creating a map.
> Add support for integer limits in map type

- lib/active_record/connection_adapters/clickhouse_adapter.rb
- lib/clickhouse-activerecord/tasks.rb
Refactoring commit (535ca30d) that altered :structure_dump to use :show_create_table made table definitions in structure.sql single-line. This restores line breaks in structure.sql.
> Restore multi-line table definitions in structure dumps

- lib/arel/visitors/clickhouse.rb
This was a small refactor we did to remove guesswork. Especially `collector.value.include?(' UPDATE ')` is prone to false positives, for example if you're working with an error column that logs query info, like `SELECT * FROM errors WHERE message ILIKE '%query failed: UPDATE table%'`. It also just felt weird to read from the collector to try to figure out what to do next.
> Use a flag to track updates/deletes in SQL visitor

- lib/active_record/connection_adapters/clickhouse/schema_statements.rb
- lib/clickhouse-activerecord/schema_dumper.rb
- spec/cluster/migration_spec.rb
- spec/single/migration_spec.rb
Currently, Ruby schema dumps export functions with `force: true` to invoke `CREATE OR REPLACE FUNCTION`, but SQL schema dumps don't do the same. This leads to errors when reloading the schema (like in a test env), when schema loading should be idempotent.
This causes `show_create_function` to return SQL with `CREATE OR REPLACE FUNCTION` instead of just `CREATE FUNCTION`.
> `CREATE OR REPLACE FUNCTION` in SQL schema dumps

- lib/clickhouse-activerecord/schema_dumper.rb
While attempting to transition my codebase to use the simple schema dump option, I noticed a few things:
1) There is a small bug in the code that generates indexes for the sql comment. It relies on the sql variable, which is only defined if we are running a non-simple dump.
2) The simple flag works great for `rails db:schema:dump:clickhouse` but gets swallowed by `rails db:migrate:clickhouse`. I thought we could short-circuit that and inject directly.
> Add support for simple schema dumping

- lib/core_extensions/active_record/relation.rb
- lib/core_extensions/arel/nodes/select_core.rb
- lib/core_extensions/arel/nodes/select_statement.rb
- spec/single/model_spec.rb
Changes the definition of `:final` and `:final!` to accept a boolean argument indicating whether to include the `FINAL` keyword. It is a code smell to have a boolean flag like this, but this keeps the API consistent with methods like `:lock`, `:readonly`, `:distinct`, etc.
This also refactors how `:final` and `:settings` are accessed in the Relation, again to be consistent with the `..._values` methods dynamically defined for other query methods. In addition to adding consistency, this also increases visibility into the Relation's state, making unit testing easier.
Lastly, this injects `:final` and `:settings` as unscopable values.
> Unscope :final and :settings
